version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert

issues:
  exclude-dirs:
    - backend/pkg/api
    - backend/internal/repository/pg/sqlc
