// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)


// Achievement defines model for Achievement.
type Achievement struct {
	BadgeIcon       string `json:"badge_icon"`
	Code            string `json:"code"`
	CtaAction       string `json:"cta_action"`
	CtaText         string `json:"cta_text"`
	CurrentProgress int    `json:"current_progress"`
	Description     string `json:"description"`
	Explanation     string `json:"explanation"`
	Id              string `json:"id"`
	IsUnlocked      bool   `json:"is_unlocked"`
	Level           int    `json:"level"`
	MaxProgress     int    `json:"max_progress"`
	Name            string `json:"name"`
}

// RecapCard defines model for RecapCard.
type RecapCard struct {
	BgGradient    string  `json:"bg_gradient"`
	CardType      string  `json:"card_type"`
	CtaAction     *string `json:"cta_action,omitempty"`
	CtaText       *string `json:"cta_text,omitempty"`
	Description   string  `json:"description"`
	Explanation   string  `json:"explanation"`
	HighlightStat string  `json:"highlight_stat"`
	IconName      string  `json:"icon_name"`
	Id            string  `json:"id"`
	Subtitle      string  `json:"subtitle"`
	Title         string  `json:"title"`
}

// RecapResponse defines model for RecapResponse.
type RecapResponse struct {
	Achievements []Achievement `json:"achievements"`
	Cards        []RecapCard   `json:"cards"`
	Metrics      UserMetrics   `json:"metrics"`
	Profile      UserProfile   `json:"profile"`
	ShareToken   string        `json:"share_token"`
}

// ShareCard defines model for ShareCard.
type ShareCard struct {
	AiTitle         string   `json:"ai_title"`
	Archetype       string   `json:"archetype"`
	AvatarUrl       string   `json:"avatar_url"`
	FullName        string   `json:"full_name"`
	TopAchievements []string `json:"top_achievements"`
	TopCategory     string   `json:"top_category"`
}

// UserMetrics defines model for UserMetrics.
type UserMetrics struct {
	ResponseSpeedSec int     `json:"response_speed_sec"`
	TopCategory      string  `json:"top_category"`
	TotalActivities  int     `json:"total_activities"`
	TotalBought      int     `json:"total_bought"`
	TotalEarned      float32 `json:"total_earned"`
	TotalPosted      int     `json:"total_posted"`
	TotalSaved       float32 `json:"total_saved"`
	TotalSold        int     `json:"total_sold"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	AvatarUrl    string    `json:"avatar_url"`
	FullName     string    `json:"full_name"`
	Id           int       `json:"id"`
	RegisteredAt time.Time `json:"registered_at"`
	UserType     string    `json:"user_type"`
	Username     string    `json:"username"`
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetAchievements Get user achievements with progress and CTA links
	//
	// Corresponds with GET /api/v1/achievements/{profileId} (the `GetAchievements` operationId).
	GetAchievements(ctx context.Context, profileId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProfiles Get all available test profiles
	//
	// Corresponds with GET /api/v1/profiles (the `GetProfiles` operationId).
	GetProfiles(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRecap Get personalized year recap for a user profile
	//
	// Corresponds with GET /api/v1/recap/{profileId} (the `GetRecap` operationId).
	GetRecap(ctx context.Context, profileId int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetShareCard Get public share card data (privacy compliant)
	//
	// Corresponds with GET /api/v1/share/{shareToken} (the `GetShareCard` operationId).
	GetShareCard(ctx context.Context, shareToken string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetAchievements Get user achievements with progress and CTA links
//
// Corresponds with GET /api/v1/achievements/{profileId} (the `GetAchievements` operationId).
func (c *Client) GetAchievements(ctx context.Context, profileId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAchievementsRequest(c.Server, profileId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetProfiles Get all available test profiles
//
// Corresponds with GET /api/v1/profiles (the `GetProfiles` operationId).
func (c *Client) GetProfiles(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProfilesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetRecap Get personalized year recap for a user profile
//
// Corresponds with GET /api/v1/recap/{profileId} (the `GetRecap` operationId).
func (c *Client) GetRecap(ctx context.Context, profileId int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRecapRequest(c.Server, profileId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetShareCard Get public share card data (privacy compliant)
//
// Corresponds with GET /api/v1/share/{shareToken} (the `GetShareCard` operationId).
func (c *Client) GetShareCard(ctx context.Context, shareToken string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetShareCardRequest(c.Server, shareToken)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAchievementsRequest constructs an http.Request for the GetAchievements method
func NewGetAchievementsRequest(server string, profileId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "profileId", profileId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/achievements/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProfilesRequest constructs an http.Request for the GetProfiles method
func NewGetProfilesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/profiles")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRecapRequest constructs an http.Request for the GetRecap method
func NewGetRecapRequest(server string, profileId int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "profileId", profileId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/recap/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetShareCardRequest constructs an http.Request for the GetShareCard method
func NewGetShareCardRequest(server string, shareToken string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "shareToken", shareToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/share/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetAchievementsWithResponse Get user achievements with progress and CTA links
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/achievements/{profileId} (the `GetAchievements` operationId).
	GetAchievementsWithResponse(ctx context.Context, profileId int, reqEditors ...RequestEditorFn) (*GetAchievementsResponse, error)

	// GetProfilesWithResponse Get all available test profiles
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/profiles (the `GetProfiles` operationId).
	GetProfilesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetProfilesResponse, error)

	// GetRecapWithResponse Get personalized year recap for a user profile
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/recap/{profileId} (the `GetRecap` operationId).
	GetRecapWithResponse(ctx context.Context, profileId int, reqEditors ...RequestEditorFn) (*GetRecapResponse, error)

	// GetShareCardWithResponse Get public share card data (privacy compliant)
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /api/v1/share/{shareToken} (the `GetShareCard` operationId).
	GetShareCardWithResponse(ctx context.Context, shareToken string, reqEditors ...RequestEditorFn) (*GetShareCardResponse, error)
}

type GetAchievementsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]Achievement
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetAchievementsResponse) GetJSON200() *[]Achievement {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetAchievementsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetAchievementsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAchievementsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAchievementsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetProfilesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]UserProfile
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetProfilesResponse) GetJSON200() *[]UserProfile {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetProfilesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetProfilesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProfilesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetProfilesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetRecapResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *RecapResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetRecapResponse) GetJSON200() *RecapResponse {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetRecapResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetRecapResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRecapResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetRecapResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetShareCardResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ShareCard
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetShareCardResponse) GetJSON200() *ShareCard {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetShareCardResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetShareCardResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetShareCardResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetShareCardResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetAchievementsWithResponse Get user achievements with progress and CTA links
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/achievements/{profileId} (the `GetAchievements` operationId).
func (c *ClientWithResponses) GetAchievementsWithResponse(ctx context.Context, profileId int, reqEditors ...RequestEditorFn) (*GetAchievementsResponse, error) {
	rsp, err := c.GetAchievements(ctx, profileId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAchievementsResponse(rsp)
}

// GetProfilesWithResponse Get all available test profiles
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/profiles (the `GetProfiles` operationId).
func (c *ClientWithResponses) GetProfilesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetProfilesResponse, error) {
	rsp, err := c.GetProfiles(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProfilesResponse(rsp)
}

// GetRecapWithResponse Get personalized year recap for a user profile
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/recap/{profileId} (the `GetRecap` operationId).
func (c *ClientWithResponses) GetRecapWithResponse(ctx context.Context, profileId int, reqEditors ...RequestEditorFn) (*GetRecapResponse, error) {
	rsp, err := c.GetRecap(ctx, profileId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRecapResponse(rsp)
}

// GetShareCardWithResponse Get public share card data (privacy compliant)
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /api/v1/share/{shareToken} (the `GetShareCard` operationId).
func (c *ClientWithResponses) GetShareCardWithResponse(ctx context.Context, shareToken string, reqEditors ...RequestEditorFn) (*GetShareCardResponse, error) {
	rsp, err := c.GetShareCard(ctx, shareToken, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetShareCardResponse(rsp)
}

// ParseGetAchievementsResponse parses an HTTP response from a GetAchievementsWithResponse call
func ParseGetAchievementsResponse(rsp *http.Response) (*GetAchievementsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAchievementsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []Achievement
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetProfilesResponse parses an HTTP response from a GetProfilesWithResponse call
func ParseGetProfilesResponse(rsp *http.Response) (*GetProfilesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProfilesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []UserProfile
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetRecapResponse parses an HTTP response from a GetRecapWithResponse call
func ParseGetRecapResponse(rsp *http.Response) (*GetRecapResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRecapResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RecapResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 404:
		break // No content-type

	}

	return response, nil
}

// ParseGetShareCardResponse parses an HTTP response from a GetShareCardWithResponse call
func ParseGetShareCardResponse(rsp *http.Response) (*GetShareCardResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetShareCardResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ShareCard
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetAchievements Get user achievements with progress and CTA links
	// (GET /api/v1/achievements/{profileId})
	GetAchievements(w http.ResponseWriter, r *http.Request, profileId int)
	// GetProfiles Get all available test profiles
	// (GET /api/v1/profiles)
	GetProfiles(w http.ResponseWriter, r *http.Request)
	// GetRecap Get personalized year recap for a user profile
	// (GET /api/v1/recap/{profileId})
	GetRecap(w http.ResponseWriter, r *http.Request, profileId int)
	// GetShareCard Get public share card data (privacy compliant)
	// (GET /api/v1/share/{shareToken})
	GetShareCard(w http.ResponseWriter, r *http.Request, shareToken string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetAchievements Get user achievements with progress and CTA links
// (GET /api/v1/achievements/{profileId})
func (_ Unimplemented) GetAchievements(w http.ResponseWriter, r *http.Request, profileId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetProfiles Get all available test profiles
// (GET /api/v1/profiles)
func (_ Unimplemented) GetProfiles(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetRecap Get personalized year recap for a user profile
// (GET /api/v1/recap/{profileId})
func (_ Unimplemented) GetRecap(w http.ResponseWriter, r *http.Request, profileId int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetShareCard Get public share card data (privacy compliant)
// (GET /api/v1/share/{shareToken})
func (_ Unimplemented) GetShareCard(w http.ResponseWriter, r *http.Request, shareToken string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetAchievements operation middleware
func (siw *ServerInterfaceWrapper) GetAchievements(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "profileId" -------------
	var profileId int

	err = runtime.BindStyledParameterWithOptions("simple", "profileId", chi.URLParam(r, "profileId"), &profileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAchievements(w, r, profileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfiles operation middleware
func (siw *ServerInterfaceWrapper) GetProfiles(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfiles(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRecap operation middleware
func (siw *ServerInterfaceWrapper) GetRecap(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "profileId" -------------
	var profileId int

	err = runtime.BindStyledParameterWithOptions("simple", "profileId", chi.URLParam(r, "profileId"), &profileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "profileId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRecap(w, r, profileId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetShareCard operation middleware
func (siw *ServerInterfaceWrapper) GetShareCard(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "shareToken" -------------
	var shareToken string

	err = runtime.BindStyledParameterWithOptions("simple", "shareToken", chi.URLParam(r, "shareToken"), &shareToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shareToken", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetShareCard(w, r, shareToken)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/profiles", wrapper.GetProfiles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/recap/{profileId}", wrapper.GetRecap)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/achievements/{profileId}", wrapper.GetAchievements)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/share/{shareToken}", wrapper.GetShareCard)
	})

	return r
}

type GetAchievementsRequestObject struct {
	ProfileId int `json:"profileId"`
}

type GetAchievementsResponseObject interface {
	VisitGetAchievementsResponse(w http.ResponseWriter) error
}

type GetAchievements200JSONResponse []Achievement

func (response GetAchievements200JSONResponse) VisitGetAchievementsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilesRequestObject struct {
}

type GetProfilesResponseObject interface {
	VisitGetProfilesResponse(w http.ResponseWriter) error
}

type GetProfiles200JSONResponse []UserProfile

func (response GetProfiles200JSONResponse) VisitGetProfilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecapRequestObject struct {
	ProfileId int `json:"profileId"`
}

type GetRecapResponseObject interface {
	VisitGetRecapResponse(w http.ResponseWriter) error
}

type GetRecap200JSONResponse RecapResponse

func (response GetRecap200JSONResponse) VisitGetRecapResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRecap404Response struct {
}

func (response GetRecap404Response) VisitGetRecapResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetShareCardRequestObject struct {
	ShareToken string `json:"shareToken"`
}

type GetShareCardResponseObject interface {
	VisitGetShareCardResponse(w http.ResponseWriter) error
}

type GetShareCard200JSONResponse ShareCard

func (response GetShareCard200JSONResponse) VisitGetShareCardResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetAchievements Get user achievements with progress and CTA links
	// (GET /api/v1/achievements/{profileId})
	GetAchievements(ctx context.Context, request GetAchievementsRequestObject) (GetAchievementsResponseObject, error)
	// GetProfiles Get all available test profiles
	// (GET /api/v1/profiles)
	GetProfiles(ctx context.Context, request GetProfilesRequestObject) (GetProfilesResponseObject, error)
	// GetRecap Get personalized year recap for a user profile
	// (GET /api/v1/recap/{profileId})
	GetRecap(ctx context.Context, request GetRecapRequestObject) (GetRecapResponseObject, error)
	// GetShareCard Get public share card data (privacy compliant)
	// (GET /api/v1/share/{shareToken})
	GetShareCard(ctx context.Context, request GetShareCardRequestObject) (GetShareCardResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetAchievements operation middleware
func (sh *strictHandler) GetAchievements(w http.ResponseWriter, r *http.Request, profileId int) {
	var request GetAchievementsRequestObject

	request.ProfileId = profileId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAchievements(ctx, request.(GetAchievementsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAchievements")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAchievementsResponseObject); ok {
		if err := validResponse.VisitGetAchievementsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProfiles operation middleware
func (sh *strictHandler) GetProfiles(w http.ResponseWriter, r *http.Request) {
	var request GetProfilesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfiles(ctx, request.(GetProfilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfiles")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProfilesResponseObject); ok {
		if err := validResponse.VisitGetProfilesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRecap operation middleware
func (sh *strictHandler) GetRecap(w http.ResponseWriter, r *http.Request, profileId int) {
	var request GetRecapRequestObject

	request.ProfileId = profileId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRecap(ctx, request.(GetRecapRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRecap")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRecapResponseObject); ok {
		if err := validResponse.VisitGetRecapResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetShareCard operation middleware
func (sh *strictHandler) GetShareCard(w http.ResponseWriter, r *http.Request, shareToken string) {
	var request GetShareCardRequestObject

	request.ShareToken = shareToken

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetShareCard(ctx, request.(GetShareCardRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetShareCard")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetShareCardResponseObject); ok {
		if err := validResponse.VisitGetShareCardResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
