// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type RecapCache struct {
	ProfileID        int32     `json:"profile_id"`
	ShareToken       string    `json:"share_token"`
	AiTitle          string    `json:"ai_title"`
	AiStory          string    `json:"ai_story"`
	Archetype        string    `json:"archetype"`
	GeneratedByAi    bool      `json:"generated_by_ai"`
	CardsJson        []byte    `json:"cards_json"`
	AchievementsJson []byte    `json:"achievements_json"`
	UpdatedAt        time.Time `json:"updated_at"`
}


type User struct {
	ID           int32     `json:"id"`
	Username     string    `json:"username"`
	FullName     string    `json:"full_name"`
	AvatarUrl    string    `json:"avatar_url"`
	UserType     string    `json:"user_type"`
	RegisteredAt time.Time `json:"registered_at"`
}

type UserActivity struct {
	ID              int32          `json:"id"`
	UserID          int32          `json:"user_id"`
	Timestamp       time.Time      `json:"timestamp"`
	ActivityType    string         `json:"activity_type"`
	Category        string         `json:"category"`
	Title           string         `json:"title"`
	Price           pgtype.Numeric `json:"price"`
	SavedAmount     pgtype.Numeric `json:"saved_amount"`
	ResponseTimeSec int32          `json:"response_time_sec"`
}
