// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteAllActivities(ctx context.Context) error
	GetRecapCacheByProfileID(ctx context.Context, profileID int32) (RecapCache, error)
	GetRecapCacheByShareToken(ctx context.Context, shareToken string) (RecapCache, error)
	GetUserActivities(ctx context.Context, userID int32) ([]UserActivity, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	InsertActivity(ctx context.Context, arg InsertActivityParams) (UserActivity, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpsertRecapCache(ctx context.Context, arg UpsertRecapCacheParams) (RecapCache, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
