// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllActivities = `-- name: DeleteAllActivities :exec
DELETE FROM user_activities
`

func (q *Queries) DeleteAllActivities(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllActivities)
	return err
}

const getRecapCacheByProfileID = `-- name: GetRecapCacheByProfileID :one
SELECT profile_id, share_token, ai_title, ai_story, archetype, generated_by_ai, cards_json, achievements_json, updated_at FROM recap_cache WHERE profile_id = $1
`

func (q *Queries) GetRecapCacheByProfileID(ctx context.Context, profileID int32) (RecapCache, error) {
	row := q.db.QueryRow(ctx, getRecapCacheByProfileID, profileID)
	var i RecapCache
	err := row.Scan(
		&i.ProfileID,
		&i.ShareToken,
		&i.AiTitle,
		&i.AiStory,
		&i.Archetype,
		&i.GeneratedByAi,
		&i.CardsJson,
		&i.AchievementsJson,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecapCacheByShareToken = `-- name: GetRecapCacheByShareToken :one
SELECT profile_id, share_token, ai_title, ai_story, archetype, generated_by_ai, cards_json, achievements_json, updated_at FROM recap_cache WHERE share_token = $1
`

func (q *Queries) GetRecapCacheByShareToken(ctx context.Context, shareToken string) (RecapCache, error) {
	row := q.db.QueryRow(ctx, getRecapCacheByShareToken, shareToken)
	var i RecapCache
	err := row.Scan(
		&i.ProfileID,
		&i.ShareToken,
		&i.AiTitle,
		&i.AiStory,
		&i.Archetype,
		&i.GeneratedByAi,
		&i.CardsJson,
		&i.AchievementsJson,
		&i.UpdatedAt,
	)
	return i, err
}


const getUserActivities = `-- name: GetUserActivities :many
SELECT id, user_id, timestamp, activity_type, category, title, price, saved_amount, response_time_sec FROM user_activities WHERE user_id = $1 ORDER BY timestamp ASC
`

func (q *Queries) GetUserActivities(ctx context.Context, userID int32) ([]UserActivity, error) {
	rows, err := q.db.Query(ctx, getUserActivities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserActivity{}
	for rows.Next() {
		var i UserActivity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Timestamp,
			&i.ActivityType,
			&i.Category,
			&i.Title,
			&i.Price,
			&i.SavedAmount,
			&i.ResponseTimeSec,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, full_name, avatar_url, user_type, registered_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.UserType,
		&i.RegisteredAt,
	)
	return i, err
}

const insertActivity = `-- name: InsertActivity :one
INSERT INTO user_activities (id, user_id, timestamp, activity_type, category, title, price, saved_amount, response_time_sec)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, timestamp, activity_type, category, title, price, saved_amount, response_time_sec
`

type InsertActivityParams struct {
	ID              int32          `json:"id"`
	UserID          int32          `json:"user_id"`
	Timestamp       time.Time      `json:"timestamp"`
	ActivityType    string         `json:"activity_type"`
	Category        string         `json:"category"`
	Title           string         `json:"title"`
	Price           pgtype.Numeric `json:"price"`
	SavedAmount     pgtype.Numeric `json:"saved_amount"`
	ResponseTimeSec int32          `json:"response_time_sec"`
}

func (q *Queries) InsertActivity(ctx context.Context, arg InsertActivityParams) (UserActivity, error) {
	row := q.db.QueryRow(ctx, insertActivity,
		arg.ID,
		arg.UserID,
		arg.Timestamp,
		arg.ActivityType,
		arg.Category,
		arg.Title,
		arg.Price,
		arg.SavedAmount,
		arg.ResponseTimeSec,
	)
	var i UserActivity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Timestamp,
		&i.ActivityType,
		&i.Category,
		&i.Title,
		&i.Price,
		&i.SavedAmount,
		&i.ResponseTimeSec,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, full_name, avatar_url, user_type, registered_at FROM users ORDER BY id ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.UserType,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRecapCache = `-- name: UpsertRecapCache :one
INSERT INTO recap_cache (profile_id, share_token, ai_title, ai_story, archetype, generated_by_ai, cards_json, achievements_json, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (profile_id) DO UPDATE SET
    share_token = EXCLUDED.share_token,
    ai_title = EXCLUDED.ai_title,
    ai_story = EXCLUDED.ai_story,
    archetype = EXCLUDED.archetype,
    generated_by_ai = EXCLUDED.generated_by_ai,
    cards_json = EXCLUDED.cards_json,
    achievements_json = EXCLUDED.achievements_json,
    updated_at = NOW()
RETURNING profile_id, share_token, ai_title, ai_story, archetype, generated_by_ai, cards_json, achievements_json, updated_at
`

type UpsertRecapCacheParams struct {
	ProfileID        int32  `json:"profile_id"`
	ShareToken       string `json:"share_token"`
	AiTitle          string `json:"ai_title"`
	AiStory          string `json:"ai_story"`
	Archetype        string `json:"archetype"`
	GeneratedByAi    bool   `json:"generated_by_ai"`
	CardsJson        []byte `json:"cards_json"`
	AchievementsJson []byte `json:"achievements_json"`
}

func (q *Queries) UpsertRecapCache(ctx context.Context, arg UpsertRecapCacheParams) (RecapCache, error) {
	row := q.db.QueryRow(ctx, upsertRecapCache,
		arg.ProfileID,
		arg.ShareToken,
		arg.AiTitle,
		arg.AiStory,
		arg.Archetype,
		arg.GeneratedByAi,
		arg.CardsJson,
		arg.AchievementsJson,
	)
	var i RecapCache
	err := row.Scan(
		&i.ProfileID,
		&i.ShareToken,
		&i.AiTitle,
		&i.AiStory,
		&i.Archetype,
		&i.GeneratedByAi,
		&i.CardsJson,
		&i.AchievementsJson,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, username, full_name, avatar_url, user_type, registered_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    username = EXCLUDED.username,
    full_name = EXCLUDED.full_name,
    avatar_url = EXCLUDED.avatar_url,
    user_type = EXCLUDED.user_type,
    registered_at = EXCLUDED.registered_at
RETURNING id, username, full_name, avatar_url, user_type, registered_at
`

type UpsertUserParams struct {
	ID           int32     `json:"id"`
	Username     string    `json:"username"`
	FullName     string    `json:"full_name"`
	AvatarUrl    string    `json:"avatar_url"`
	UserType     string    `json:"user_type"`
	RegisteredAt time.Time `json:"registered_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.FullName,
		arg.AvatarUrl,
		arg.UserType,
		arg.RegisteredAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.UserType,
		&i.RegisteredAt,
	)
	return i, err
}
